### ISSUE TITLE
The app doesn't write the filename properly when downloading.

### ISSUE THREAD

**Issue by Ahmneo** [mansuf/zippyshare-downloader#4]
Here's some code output I got:

[INFO] Fetching URL "https://www108.zippyshare.com/v/kt8db8LC/file.html"
[INFO] Parsing info
[INFO] Getting Download URL from "https://www108.zippyshare.com/v/kt8db8LC/file.html"
[INFO] Downloading "<img alt="file name" src="/fileName?key=kt8db8LC&amp;size=small" style="margin-left: 10px;"/>"
Downloading data from https://www108.zippyshare.com/d/kt8db8LC/271977/Prison.Break.S01E01.Pilot.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.part01.rar (500.0 MB)

file_sizes:   3%|▉                          | 17.5M/524M [00:01<00:51, 9.79MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/zippyshare-downloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__main__.py", line 21, in main
    print(z.extract_info(args.ZIPPYSHARE_URL, download=True))
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 184, in extract_info
    return self._extract_info(url, download=download)
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 158, in _extract_info
    dl(info['download_url'], info['name_file'], progressbar=self._progress_bar, verbose=self._verbose, replace=self._replace)
  File "/usr/local/lib/python3.7/dist-packages/download/download.py", line 124, in download
    progressbar=progressbar,
  File "/usr/local/lib/python3.7/dist-packages/download/download.py", line 254, in _fetch_file
    ncols=80,
  File "/usr/local/lib/python3.7/dist-packages/download/download.py", line 381, in _get_http
    chunk = response.read(chunk_size)
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by mansuf** [comment]
I think zippyshare is changing their code, again...

When you try to download a file, the module using filename from `name_file` that extracted from `Zippyshare.extract_info()`, unfortunately Zippyshare is changing their code, so when the module is trying to grab `name_file`, the module is broke

So here my suggestions until this issue is fixed:

### if you want to download from python script
- create a python script file
- import `zippyshare-downloader` module
- extract the download link, using `Zippyshare.extract_info('give zippyshare url here', download=False)` (but DO NOT download the file yet)
- import `download()` function `download` module
- and then call `download()` function and give required arguments

see example snippets code below

```python

from zippyshare_downloader import Zippyshare

z = Zippyshare()

info = z.extract_info('https://www108.zippyshare.com/v/kt8db8LC/file.html', download=False)

from download import download

# you can pass verbose, progress_bar, and replace arguments as well
download(info['download_url'], 'give your custom filename here')

# and that's it.
```

### if you want to download from any browser (MUST SAME IP)
- in terminal do `zippyshare-dl "give zippyshare url here" --no-download`
- copy the download link from `download_url` in terminal output
- paste in your browser, and then press enter.

**Comment by Ahmneo** [comment]
Thanks. That worked, but now I need to add all the rars to the script and add each name manually. I'll wait until the issue is solved.

**Comment by Ahmneo** [comment]
I don't know python, but isn't there an OCR module like pytesseract, that you can embed into this app?

**Comment by mansuf** [comment]
i don't think this is a optimal solution, since pytesseract require additional binary to run it.

**Comment by mansuf** [comment]
This issue is fixed in commit https://github.com/mansuf/zippyshare-downloader/commit/bb3d9406e984c08930375365276db7eb4948e7df, the update will be released (v0.0.16).

Sorry for taking to long. I was busy for school.
![image](https://user-images.githubusercontent.com/43638783/113476692-2cfa9100-94a7-11eb-9160-36efabf74726.png)

**Comment by mansuf** [comment]
The update has been released, please update your `zippyshare-downloader` to latest version (v0.0.16)

**Comment by Ahmneo** [comment]
Thank you.
